setup-env-internal: validate machine and distro selection
Check that the -m and -d options specify recognized
machine and distro settings, respectively, when setting
up a new build directory.

Signed-off-by: Matt Madison <matt@madison.systems>

diff --git a/scripts-setup/setup-env-internal b/scripts-setup/setup-env-internal
--- a/scripts-setup/setup-env-internal
+++ b/scripts-setup/setup-env-internal
@@ -112,8 +112,22 @@ if [ ! -e $BUILDDIR/conf/local.conf ]; then
         echo "TD_RC=1"
         exit 1
     fi
+    if ! machine_list | grep -q "$MACHINE"; then
+	echo "ERROR: machine \"$MACHINE\" not found" >&2
+	echo "Available MACHINEs:" >&2
+	machine_list >&2
+	echo "TD_RC=1"
+	exit 1
+    fi
     if [ -z "$DISTRO" ]; then
         DISTRO=$DISTRO_DEFAULT
+    fi
+    if ! distro_list | grep -q "$DISTRO"; then
+	echo "ERROR: distro \"$DISTRO\" not found" >&2
+	echo "Available DISTROs:" >&2
+	distro_list >&2
+	echo "TD_RC=1"
+	exit 1
     fi
     LAYERPATH=$(distro_path $DISTRO)
     NEEDSETUP=yes
